version: '3.1'

services:
  wordpress:
    depends_on:
      - db
      # - redis
    image: wordpress:latest
    container_name: wordpres_wptest
    volumes:
      - ./www/:/var/www/html/
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_PASSWORD: p4ssw0rd!
      WORDPRESS_DB_NAME: db_wordpress
      WORDPRESS_TABLE_PREFIX: dx36fd_
    ports:
      - 8585:80
    networks:
      - wptest_network
  db:
    image: mariadb:latest
    container_name: wptest_mariadb
    volumes:
       - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: p4ssw0rd!
    networks:
      - wptest_network
  # redis:
  #   image: redis:alpine
  #   networks:
  #     - wptest_network
networks:
  wptest_network:
volumes:
  db_data: